### ISSUE TITLE
row - select and col - select

### ISSUE THREAD

**Issue by SongFGH** [khanhhhh/ladies#1]
Hi, bro,
in your code, 
sampler->ladies_sampler:
row - select and col - select the lap_matrix (U), and then divided by the sampled probability for unbiased - sampling.
adj = lap_matrix [ previous_nodes , :][: , after_nodes ]
adj = adj. multiply (1/ p[ after_nodes ])

However, the Original code only col-select the lap_matrix (U)! 

I can not understand, can you explain more?

**Comment by khanhhhh** [comment]
`adj = lap_matrix [ previous_nodes , :][: , after_nodes ]`
represents the row-selection matrix and colum-selection matrix Q in the original paper.
https://arxiv.org/pdf/1911.07323.pdf
3.2, step 5, Algorithm 1
